export const LogEvent = {
  IdempotencyDuplicate: "idem.duplicate",
  TransactionCreated: "txn.created",
  TransactionReversed: "txn.reversed",
  TransactionUpdated: "txn.updated",
  TransferCreated: "transfer.created",
  TransferReversed: "transfer.reversed",
  ImportBatchParsed: "import.batch_parsed",
  ImportBatchParseFailed: "import.batch_parse_failed",
  NotificationDelivered: "notification.delivered",
  NotificationDeliveryFailed: "notification.delivery_failed",
  NotificationSweepEnqueued: "notification.sweep_enqueued",
  RecurringMaterialized: "recurring.materialized",
  RecurringMaterializeFailed: "recurring.materialize_failed",
  RollupsRefreshed: "rollups.refreshed",
  RollupRefreshFailed: "rollups.refresh_failed",
  BalanceDriftDetected: "balances.drift_detected",
  BalancesVerified: "balances.verified",
  MetricsWriteFailed: "observability.metrics_write_failed",
  StagedRowsCleaned: "imports.staged_rows_cleaned",
  SpendingWarningsScheduled: "spending_warnings.scheduled",
  SpendingWarningsAnalyzed: "spending_warnings.analyzed",
  SpendingWarningsAnalyzeFailed: "spending_warnings.analyze_failed",
  GoalAchieved: "goal.achieved",
  GoalProgressCheckFailed: "goal.progress_check_failed",
  GoalsProgressChecked: "goals.progress_checked",
  BudgetAlertEnqueued: "budget.alert_enqueued",
  BudgetAlertCheckFailed: "budget.alert_check_failed",
  BudgetAlertsChecked: "budgets.alerts_checked",
  WorkerHeartbeatFailed: "worker.heartbeat_failed",
  WorkerStopping: "worker.stopping",
  WorkerStopped: "worker.stopped"
} as const;

export type LogEvent = (typeof LogEvent)[keyof typeof LogEvent];
