import type { ReactNode } from "react";

import { monthLabel } from "../model/month";

export function ReportEmptyState({
  month,
  isInProgress
}: Readonly<{ month: string; isInProgress: boolean }>): ReactNode {
  return (
    <div className="flex flex-col items-center rounded-[18px] border border-dashed border-border bg-surface-elevated px-6 py-20 text-center">
      <div className="mb-5 grid h-15.5 w-15.5 place-items-center rounded-2xl bg-surface-muted text-3xl text-foreground-muted">
        ◷
      </div>
      <p className="text-xl font-bold text-foreground">No rollup for {monthLabel(month)}</p>
      <p className="mt-2 max-w-md text-sm leading-relaxed text-foreground-muted">
        {isInProgress
          ? "This month is still in progress. Rollups are generated after the month closes — check back once it's complete."
          : "This month was never computed. Rollups are a cached summary generated by a scheduled job, and this period predates yours."}
      </p>
    </div>
  );
}
