export const ErrorCodes = [
  "common.validation_failed",
  "common.not_found",
  "common.invalid_cursor",
  "common.idempotency_conflict",
  "common.internal",
  "common.dependency_unavailable",
  "money.out_of_range",
  "auth.unauthenticated",
  "auth.insufficient_scope",
  "auth.rate_limited",
  "txn.already_reversed",
  "txn.transfer_metadata_requires_group",
  "category.parent_kind_mismatch",
  "category.kind_mismatch",
  "category.hierarchy_conflict",
  "category.name_conflict",
  "category.in_use",
  "asset.invalid_valuation_sign",
  "goal.funding_source_in_use",
  "goal.invalid_order",
  "import.invalid_file",
  "import.already_committed",
  "import.invalid_state",
  "bill.invalid_account_type",
  "bill.not_reconciled",
  "bill.overpayment",
  "bill.invalid_statement_file",
  "bill.statement_not_ready",
  "bill.unresolved_statement",
  "bill.already_reconciled",
  "bill.invalid_payment_source",
  "recurring.no_occurrences",
  "recurring.reconciliation_already_resolved",
  "recurring.invalid_reconciliation_resolution",
  "pending_transaction.already_resolved"
] as const;

export type ErrorCode = (typeof ErrorCodes)[number];
